include_guard(GLOBAL)
# Usage:
# fortuno_discover_tests(target,
#     [USE_PRE_TEST_DISCOVERY] # (Optional) flag to use pre-test discovery mode (default is post-build)
#     [TEST_PREFIX prefix]     # (Optional) prefix for test names
#     [TEST_SUFFIX suffix]     # (Optional) suffix for test names
#     [TEST_PATTERN pattern]   # (Optional) pattern to filter tests (default is none, i.e. all tests)
#     [WORKING_DIRECTORY dir]  # (Optional) working directory for tests (default is CMAKE_CURRENT_BINARY_DIR)
# Description:
# Query the Fortuno test executable for its list of tests and individually register them with CTest.
# Querying is performed either at build time (default POST_BUILD mode) or at test time (PRE_TEST_DISCOVERY mode).
# In the former case, an additional testlist.cmake file is generated after building the target to be included by CTest.
# In the latter case, the test discovery is performed anew each time tests are run.
function(fortuno_discover_tests target)
    if (NOT TARGET ${target})
        message(FATAL_ERROR "fortuno_discover_tests: target '${target}' does not exist")
    endif ()
    
    # Parse arguments and apply defaults
    cmake_parse_arguments(ARG "USE_PRE_TEST_DISCOVERY" "TEST_PREFIX;TEST_SUFFIX;TEST_PATTERN;WORKING_DIRECTORY" "" ${ARGN})

    if (ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "fortuno_discover_tests: Unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
    endif ()

    if (NOT DEFINED ARG_WORKING_DIRECTORY)
        set(ARG_WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    endif ()


    set(discovery_script "${CMAKE_CURRENT_BINARY_DIR}/discover_tests_${target}_$<CONFIG>.cmake")
    set(dispatch_script "${CMAKE_CURRENT_BINARY_DIR}/dispatch_discover_${target}.cmake")
    set(testlist_file "${CMAKE_CURRENT_BINARY_DIR}/testlist_${target}_$<CONFIG>.cmake")

    # Point ctest to the dispatch script which either loads the testlist file or 
    # Runs the discovery step.
    set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES "${dispatch_script}")
    if (ARG_USE_PRE_TEST_DISCOVERY)
        set(dispatch_prefix "${CMAKE_CURRENT_BINARY_DIR}/discover_tests_${target}_")
    else()
        set(dispatch_prefix "${CMAKE_CURRENT_BINARY_DIR}/testlist_${target}_")

        # Generate the testlist POST_BUILD
        add_custom_command(
            TARGET ${target} 
            POST_BUILD
            COMMAND ${CMAKE_COMMAND} -P "${discovery_script}"
            WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
            BYPRODUCTS "${testlist_file}"
            VERBATIM
        )
    endif ()

    
    # The discovery script is created at generation time to resolve $<TARGET_FILE:...>.
    # This script will be run at build time (default) or test time (USE_PRE_TEST_DISCOVERY)
    # to discover and either directly add or generate a testlist.cmake file.
    set(discovery_script_content "\
# Auto-generated test discovery script generated by fortuno_discover_tests(${target}).
# $<CONFIG>
cmake_policy(PUSH)
cmake_policy(SET CMP0012 NEW) # Enable bools
set(working_dir \"${ARG_WORKING_DIRECTORY}\")
set(test_prefix \"${ARG_TEST_PREFIX}\")
set(test_suffix \"${ARG_TEST_SUFFIX}\")
set(test_executable \"$<TARGET_FILE:${target}>\")

set(discover_command \"\${test_executable}\" --list ${ARG_TEST_PATTERN})

# Query Fortuno executable for tests
if (NOT EXISTS \"\${test_executable}\")
    message(WARNING \"Could not find test executable: \${test_executable}. (Have you built the project?) Skipping test discovery.\")
    cmake_policy(POP)
    return()
endif ()

execute_process(
    COMMAND \${discover_command}
    OUTPUT_VARIABLE output_string
    ERROR_VARIABLE error_string
    RESULT_VARIABLE returncode
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
if (returncode)
    message(FATAL_ERROR \"Test discovery failed for ${target}, \${discover_command} returned \${returncode}.\\nOutput:\\n\${error_string}\")
    cmake_policy(POP)
    return()
endif ()

# Convert newlines to CMake semicolon list
string(REGEX REPLACE \"(\\r\\n|\\n)\" \";\" testlist \"\${output_string}\")

# Notify user if no tests found (e.q. due to bad pattern)
if (testlist STREQUAL \"\")
    message(WARNING \"No tests found for ${target} with pattern '${ARG_TEST_PATTERN}'.\")
    cmake_policy(POP)
    return()
endif ()

if (${ARG_USE_PRE_TEST_DISCOVERY})
    message(STATUS \"Registering \${testlist} tests for ${target} (PRE_TEST discovery mode)...\")
else()
    file(WRITE \"${testlist_file}\" \"# Auto-generated test list for ${target} (POST_BUILD discovery mode)\\n\")
endif ()


# Actually discover each test
foreach(test_name IN LISTS testlist)
    set(ctest_name \"\${test_prefix}\${test_name}\${test_suffix}\")
    set(test_command \${cross_emulator} \"\${test_executable}\" \"\${test_name}\")

    # Either write tests to file, or add directly
    if (${ARG_USE_PRE_TEST_DISCOVERY})
        add_test(\"\${ctest_name}\" \${test_command})
        set_tests_properties(\"\${ctest_name}\" PROPERTIES WORKING_DIRECTORY \"\${working_dir}\")
    else()
        file(APPEND \"${testlist_file}\" \"add_test(\\\"\${ctest_name}\\\" \${test_command})\\n\")
        file(APPEND \"${testlist_file}\" \"set_tests_properties(\\\"\${ctest_name}\\\" PROPERTIES WORKING_DIRECTORY \\\"\${working_dir}\\\")\\n\")
    endif ()
endforeach()
cmake_policy(POP)
    ") # end discovery_script_content
    
    set(dispatch_script_content "\
# Test discovery dispatch script generated by fortuno_discover_tests(${target}).
cmake_policy(PUSH)
cmake_policy(SET CMP0012 NEW)

if (DEFINED CTEST_CONFIGURATION_TYPE AND CTEST_CONFIGURATION_TYPE)
    set(script_path \"${dispatch_prefix}\${CTEST_CONFIGURATION_TYPE}.cmake\")
else()
    set(script_path \"${dispatch_prefix}${CMAKE_BUILD_TYPE}.cmake\")
endif ()

if (EXISTS \"\${script_path}\")
    include(\"\${script_path}\")
endif ()
cmake_policy(POP)
") # end dispatch_script_content

    file(WRITE "${dispatch_script}" "${dispatch_script_content}")
    file(GENERATE OUTPUT "${discovery_script}" CONTENT "${discovery_script_content}")


endfunction()

